spring:
  config:
    import: optional:aws-secretsmanager:/ # To load application running from local machine you need two correct setting files (config, credentials) in c:\Users\User\.aws\ folder
#  application:
#    name: config-client
application:
  customer: cash
aws:
  secretsmanager:
    enabled: false
    prefix:
    name: config-client
    profile-separator: "-"